# Generated by Django 3.0.6 on 2020-05-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of note', max_length=200)),
                ('description', models.TextField(help_text='description of note')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Note',
                'db_table': 'note',
            },
        ),
    ]
